### ISSUE TITLE
License missing.

### ISSUE THREAD

**Issue by xuv** [Nurgak/Universal-vertex-module#1]
Great project. Thanks for sharing.

Since, [according to this page](http://www.thingiverse.com/thing:1080119), you're releasing this project as CC-0 (Public Domain), it would be good if you added this info in the repo also.

**Comment by xuv** [comment]
Oops. My bad.  
License is mentioned in the .jscad file.
```// license : LGPL``` 
Isn't this conflicting with the CC-0 you chose for Thingiverse?  
Or I guess this is an interesting legal question, the outcome of the code (aka, a 3D file) is licensed under CC-0, but the code itself is LGPL?

**Comment by Nurgak** [comment]
How come I didn't see this issue until now? Yeah that's the idea, the part on Thingyverse is under Public Domain licence, but the code is under LGPL.

I'm closing the issue as there is nothing to solve.

**Comment by xuv** [comment]
Thanks for replying. Not to be rude or anything, but would you mind explaining why you choose those two different licenses for the project? I find it very interesting to have the code in one license and the output of the code in another, especially in a case like this. What made you come to this conclusion? Thank you.

**Comment by Nurgak** [comment]
The way I see it: you have a bunch on stuff (tree branches, PVC tubes, crayons...), you print custom vertices (square, round, different sizes) to interconnect you stuff in order to create some kind of construction. In this process you need modularity and flexibility in the vertices, perhaps every module will be different.

Legally speaking the part is simple and easy to model in any CAD software, no reason to limit it in any way - I am not the first one to think of it anyway. The code is the driving force behind it and I would like improvements to the code to remain accessible to everyone.

**Comment by xuv** [comment]
Thx for taking the time to respond. Have a nice day.
